# Generated by Django 5.2.1 on 2025-05-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reminders",
            new_name="Reminder",
        ),
        migrations.AlterModelOptions(
            name="reminder",
            options={"verbose_name_plural": "Reminders"},
        ),
    ]
